# max_width = 240
# ideal_width = 240
# tab_spaces = 4
# fn_call_width = 0
# struct_lit_width = 0
# impl_empty_single_line = false
# fn_empty_single_line = false
# fn_single_line = false
# fn_args_density = Vertical
# struct_lit_multiline_style = ForceMulti
# reorder_imports = true
# reorder_imported_names = true
# single_line_if_else_max_width = 0
