[package]
name = "addon_gui"
version = "0.1.0"
authors = ["yelikdev@gmail.com <Kiley Owen>"]

[dependencies]
base_comps = { path="../base_comps" }
event_core = { path="../event_core" }
base_events = { path="../base_events" }
specs = "0.7.0"
utils = { path="../utils" }
