[package]
name = "base_events"
version = "0.1.0"
authors = ["Kiley Owen"]

[dependencies]
utils = { path="../utils" }
graphics = { path="../graphics" }

[features]
g_glutin = ["graphics/g_glutin"]
g_sdl2 = ["graphics/g_sdl2"]
