[package]
name = "game-6"
version = "0.1.0"
authors = ["yelikdev@gmail.com <Kiley Owen>"]

[dependencies]
log = "0.3.6"
env_logger = "0.3.5"

core = { path="../core" }
configger = { path="../configger" }

[features]
g_glutin = ["core/g_glutin"]
g_sdl2 = ["core/g_sdl2"]

default = ["g_glutin"]
